apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth ## selects pods with label app: auth
  type: ClusterIP ## default type, exposes the service on a cluster-internal IP, making it only reachable from within the cluster
  ports:
    - protocol: TCP
      port: 80 ## port exposed by the service, accessible within the cluster
      targetPort: 80 ## port on which the container is listening. 80 because our auth app is configured to listen on this port