apiVersion: apps/v1
kind: Deployment
metadata: 
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
      - name: tasks
        image: docker.io/pytsmarkiyan/kub-demo-tasks:latest
        env:
        - name: AUTH_ADDRESS
          value: "auth-service.default" # service name in kubernetes cluster DNS + namespace
        - name: TASKS_FOLDER
          value: "tasks"