apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  selector:
    app: tasks ## selects pods with label app: tasks
  #type: ClusterIP ## default type, exposes the service on a cluster-internal IP, making it only reachable from within the cluster
  type: LoadBalancer ## exposes the service externally using a cloud provider's load balancer
  ports:
    - protocol: TCP
      port: 8000 ## port exposed by the service, accessible within the cluster
      targetPort: 8000 ## port on which the container is listening. 8000 because our app is configured to listen on this port