apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users ## selects pods with label app: users
  #type: ClusterIP ## default type, exposes the service on a cluster-internal IP, making it only reachable from within the cluster
  type: LoadBalancer ## exposes the service externally using a cloud provider's load balancer
  ports:
    - protocol: TCP
      port: 8080 ## port exposed by the service, accessible within the cluster
      targetPort: 8080 ## port on which the container is listening. 8080 because our app is configured to listen on this port